/*
 * try/catch
 * Помилки фази парсингу опрацювати неможна. Тільки помилки фази виконання.
 * Обєкт помилки
 * try/catch працює тільки з синхронним кодом
 * Опрацювання помилок в асинхронному коді
 */

// console.log('First');

// setTimeout(() => {
//   try {
//     const username = 'Oleksii';

//     username = 'Elva';
//   } catch (err) {
//     console.log(err);
//   }

//   console.log('Hello');
// }, 1000);

// console.log('Second');
